/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'eyeTest' : IDL.Null,
  'combined' : IDL.Null,
  'frameTryOn' : IDL.Null,
});
export const PriceInfo = IDL.Record({
  'total' : IDL.Nat,
  'baseFee' : IDL.Nat,
  'addOns' : IDL.Nat,
});
export const RepairType = IDL.Variant({
  'adjustment' : IDL.Null,
  'other' : IDL.Null,
  'screwTightening' : IDL.Null,
  'lensReplacement' : IDL.Null,
});
export const RentalItem = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'deposit' : IDL.Nat,
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
  'category' : IDL.Text,
});
export const Provider = IDL.Record({
  'id' : IDL.Principal,
  'active' : IDL.Bool,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'availability' : IDL.Text,
  'serviceAreas' : IDL.Text,
  'services' : IDL.Vec(ServiceType),
});
export const BookingStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const BookingType = IDL.Variant({
  'rental' : IDL.Null,
  'repair' : IDL.Null,
  'mobileOptician' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Int,
  'status' : BookingStatus,
  'serviceType' : IDL.Opt(ServiceType),
  'provider' : IDL.Opt(IDL.Principal),
  'customer' : IDL.Principal,
  'createdAt' : IDL.Int,
  'repairType' : IDL.Opt(RepairType),
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
  'bookingType' : BookingType,
  'preferredTime' : IDL.Text,
  'details' : IDL.Text,
  'price' : PriceInfo,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignProviderToBooking' : IDL.Func([IDL.Int, IDL.Principal], [], []),
  'createOpticianBooking' : IDL.Func(
      [ServiceType, IDL.Text, IDL.Text, IDL.Text, PriceInfo],
      [IDL.Int],
      [],
    ),
  'createRentalBooking' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Text, PriceInfo],
      [IDL.Int],
      [],
    ),
  'createRepairBooking' : IDL.Func(
      [RepairType, IDL.Text, IDL.Text, IDL.Text, PriceInfo],
      [IDL.Int],
      [],
    ),
  'findAvailableRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Int], [Booking], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getProvider' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
  'getProviderBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getRentalCatalog' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onboardProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ServiceType), IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Int, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'eyeTest' : IDL.Null,
    'combined' : IDL.Null,
    'frameTryOn' : IDL.Null,
  });
  const PriceInfo = IDL.Record({
    'total' : IDL.Nat,
    'baseFee' : IDL.Nat,
    'addOns' : IDL.Nat,
  });
  const RepairType = IDL.Variant({
    'adjustment' : IDL.Null,
    'other' : IDL.Null,
    'screwTightening' : IDL.Null,
    'lensReplacement' : IDL.Null,
  });
  const RentalItem = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'deposit' : IDL.Nat,
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Provider = IDL.Record({
    'id' : IDL.Principal,
    'active' : IDL.Bool,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'availability' : IDL.Text,
    'serviceAreas' : IDL.Text,
    'services' : IDL.Vec(ServiceType),
  });
  const BookingStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const BookingType = IDL.Variant({
    'rental' : IDL.Null,
    'repair' : IDL.Null,
    'mobileOptician' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Int,
    'status' : BookingStatus,
    'serviceType' : IDL.Opt(ServiceType),
    'provider' : IDL.Opt(IDL.Principal),
    'customer' : IDL.Principal,
    'createdAt' : IDL.Int,
    'repairType' : IDL.Opt(RepairType),
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
    'bookingType' : BookingType,
    'preferredTime' : IDL.Text,
    'details' : IDL.Text,
    'price' : PriceInfo,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignProviderToBooking' : IDL.Func([IDL.Int, IDL.Principal], [], []),
    'createOpticianBooking' : IDL.Func(
        [ServiceType, IDL.Text, IDL.Text, IDL.Text, PriceInfo],
        [IDL.Int],
        [],
      ),
    'createRentalBooking' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Text, PriceInfo],
        [IDL.Int],
        [],
      ),
    'createRepairBooking' : IDL.Func(
        [RepairType, IDL.Text, IDL.Text, IDL.Text, PriceInfo],
        [IDL.Int],
        [],
      ),
    'findAvailableRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Int], [Booking], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getProvider' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
    'getProviderBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getRentalCatalog' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onboardProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ServiceType), IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Int, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };