/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'eyeTest' : IDL.Null,
  'combined' : IDL.Null,
  'frameTryOn' : IDL.Null,
});
export const PriceInfo = IDL.Record({
  'total' : IDL.Nat,
  'baseFee' : IDL.Nat,
  'addOns' : IDL.Nat,
});
export const RepairType = IDL.Variant({
  'adjustment' : IDL.Null,
  'other' : IDL.Null,
  'screwTightening' : IDL.Null,
  'lensReplacement' : IDL.Null,
});
export const RentalItem = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'deposit' : IDL.Nat,
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
  'category' : IDL.Text,
});
export const Provider = IDL.Record({
  'id' : IDL.Principal,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'phone' : IDL.Text,
  'serviceAreas' : IDL.Text,
  'services' : IDL.Vec(ServiceType),
});
export const BookingStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const BookingType = IDL.Variant({
  'rental' : IDL.Null,
  'repair' : IDL.Null,
  'mobileOptician' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Int,
  'status' : BookingStatus,
  'serviceType' : IDL.Opt(ServiceType),
  'provider' : IDL.Opt(IDL.Principal),
  'customer' : IDL.Principal,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'repairTypes' : IDL.Opt(IDL.Vec(RepairType)),
  'address' : IDL.Opt(IDL.Text),
  'bookingType' : BookingType,
  'preferredTime' : IDL.Opt(IDL.Text),
  'details' : IDL.Opt(IDL.Text),
  'price' : PriceInfo,
});
export const FrameShape = IDL.Variant({
  'rectangular' : IDL.Null,
  'oval' : IDL.Null,
  'square' : IDL.Null,
  'aviator' : IDL.Null,
  'wayfarer' : IDL.Null,
  'catEye' : IDL.Null,
  'round' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'framePreferences' : IDL.Opt(IDL.Vec(FrameShape)),
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'prescriptionPicture' : IDL.Opt(ExternalBlob),
});
export const LogMobileNumberVerification = IDL.Record({
  'mobileNumber' : IDL.Text,
  'verifiedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignProviderToBooking' : IDL.Func([IDL.Int, IDL.Principal], [], []),
  'calculateProfileCompletion' : IDL.Func([], [IDL.Nat], ['query']),
  'createOpticianBooking' : IDL.Func(
      [
        ServiceType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        PriceInfo,
        IDL.Text,
      ],
      [IDL.Int],
      [],
    ),
  'createRentalBooking' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Text, PriceInfo],
      [IDL.Int],
      [],
    ),
  'createRepairBooking' : IDL.Func(
      [
        IDL.Vec(RepairType),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        PriceInfo,
      ],
      [IDL.Int],
      [],
    ),
  'findAvailableRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Int], [Booking], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMobileNumberVerifications' : IDL.Func(
      [],
      [IDL.Vec(LogMobileNumberVerification)],
      ['query'],
    ),
  'getProvider' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
  'getProviderBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getRentalCatalog' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMobileNumberVerification' : IDL.Func([IDL.Text], [], []),
  'onboardProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ServiceType), IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Int, BookingStatus], [], []),
  'updateFramePreferences' : IDL.Func([IDL.Vec(FrameShape)], [], []),
  'updatePrescriptionPicture' : IDL.Func([ExternalBlob], [], []),
  'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'eyeTest' : IDL.Null,
    'combined' : IDL.Null,
    'frameTryOn' : IDL.Null,
  });
  const PriceInfo = IDL.Record({
    'total' : IDL.Nat,
    'baseFee' : IDL.Nat,
    'addOns' : IDL.Nat,
  });
  const RepairType = IDL.Variant({
    'adjustment' : IDL.Null,
    'other' : IDL.Null,
    'screwTightening' : IDL.Null,
    'lensReplacement' : IDL.Null,
  });
  const RentalItem = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'deposit' : IDL.Nat,
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Provider = IDL.Record({
    'id' : IDL.Principal,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'phone' : IDL.Text,
    'serviceAreas' : IDL.Text,
    'services' : IDL.Vec(ServiceType),
  });
  const BookingStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const BookingType = IDL.Variant({
    'rental' : IDL.Null,
    'repair' : IDL.Null,
    'mobileOptician' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Int,
    'status' : BookingStatus,
    'serviceType' : IDL.Opt(ServiceType),
    'provider' : IDL.Opt(IDL.Principal),
    'customer' : IDL.Principal,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'repairTypes' : IDL.Opt(IDL.Vec(RepairType)),
    'address' : IDL.Opt(IDL.Text),
    'bookingType' : BookingType,
    'preferredTime' : IDL.Opt(IDL.Text),
    'details' : IDL.Opt(IDL.Text),
    'price' : PriceInfo,
  });
  const FrameShape = IDL.Variant({
    'rectangular' : IDL.Null,
    'oval' : IDL.Null,
    'square' : IDL.Null,
    'aviator' : IDL.Null,
    'wayfarer' : IDL.Null,
    'catEye' : IDL.Null,
    'round' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'framePreferences' : IDL.Opt(IDL.Vec(FrameShape)),
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'prescriptionPicture' : IDL.Opt(ExternalBlob),
  });
  const LogMobileNumberVerification = IDL.Record({
    'mobileNumber' : IDL.Text,
    'verifiedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignProviderToBooking' : IDL.Func([IDL.Int, IDL.Principal], [], []),
    'calculateProfileCompletion' : IDL.Func([], [IDL.Nat], ['query']),
    'createOpticianBooking' : IDL.Func(
        [
          ServiceType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          PriceInfo,
          IDL.Text,
        ],
        [IDL.Int],
        [],
      ),
    'createRentalBooking' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Text, PriceInfo],
        [IDL.Int],
        [],
      ),
    'createRepairBooking' : IDL.Func(
        [
          IDL.Vec(RepairType),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          PriceInfo,
        ],
        [IDL.Int],
        [],
      ),
    'findAvailableRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Int], [Booking], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMobileNumberVerifications' : IDL.Func(
        [],
        [IDL.Vec(LogMobileNumberVerification)],
        ['query'],
      ),
    'getProvider' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
    'getProviderBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getRentalCatalog' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMobileNumberVerification' : IDL.Func([IDL.Text], [], []),
    'onboardProvider' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ServiceType),
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Int, BookingStatus], [], []),
    'updateFramePreferences' : IDL.Func([IDL.Vec(FrameShape)], [], []),
    'updatePrescriptionPicture' : IDL.Func([ExternalBlob], [], []),
    'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };