/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : [] | [ServiceType],
  'provider' : [] | [Principal],
  'customer' : Principal,
  'createdAt' : bigint,
  'repairType' : [] | [RepairType],
  'updatedAt' : bigint,
  'address' : string,
  'bookingType' : BookingType,
  'preferredTime' : string,
  'details' : string,
  'price' : PriceInfo,
}
export type BookingStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type BookingType = { 'rental' : null } |
  { 'repair' : null } |
  { 'mobileOptician' : null };
export interface PriceInfo {
  'total' : bigint,
  'baseFee' : bigint,
  'addOns' : bigint,
}
export interface Provider {
  'id' : Principal,
  'active' : boolean,
  'contact' : string,
  'name' : string,
  'availability' : string,
  'serviceAreas' : string,
  'services' : Array<ServiceType>,
}
export interface RentalItem {
  'id' : bigint,
  'name' : string,
  'deposit' : bigint,
  'available' : boolean,
  'pricePerDay' : bigint,
  'category' : string,
}
export type RepairType = { 'adjustment' : null } |
  { 'other' : null } |
  { 'screwTightening' : null } |
  { 'lensReplacement' : null };
export type ServiceType = { 'eyeTest' : null } |
  { 'combined' : null } |
  { 'frameTryOn' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignProviderToBooking' : ActorMethod<[bigint, Principal], undefined>,
  'createOpticianBooking' : ActorMethod<
    [ServiceType, string, string, string, PriceInfo],
    bigint
  >,
  'createRentalBooking' : ActorMethod<
    [bigint, bigint, string, PriceInfo],
    bigint
  >,
  'createRepairBooking' : ActorMethod<
    [RepairType, string, string, string, PriceInfo],
    bigint
  >,
  'findAvailableRentalItems' : ActorMethod<[], Array<RentalItem>>,
  'getActiveProviders' : ActorMethod<[], Array<Provider>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerBookings' : ActorMethod<[], Array<Booking>>,
  'getProvider' : ActorMethod<[Principal], [] | [Provider]>,
  'getProviderBookings' : ActorMethod<[], Array<Booking>>,
  'getRentalCatalog' : ActorMethod<[], Array<RentalItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'onboardProvider' : ActorMethod<
    [string, string, string, Array<ServiceType>, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];