/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RentalItem {
    id: bigint;
    name: string;
    deposit: bigint;
    available: boolean;
    pricePerDay: bigint;
    category: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    serviceType?: ServiceType;
    provider?: Principal;
    customer: Principal;
    createdAt: bigint;
    repairType?: RepairType;
    updatedAt: bigint;
    address: string;
    bookingType: BookingType;
    preferredTime: string;
    details: string;
    price: PriceInfo;
}
export interface Provider {
    id: Principal;
    active: boolean;
    contact: string;
    name: string;
    availability: string;
    serviceAreas: string;
    services: Array<ServiceType>;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface PriceInfo {
    total: bigint;
    baseFee: bigint;
    addOns: bigint;
}
export enum BookingStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum BookingType {
    rental = "rental",
    repair = "repair",
    mobileOptician = "mobileOptician"
}
export enum RepairType {
    adjustment = "adjustment",
    other = "other",
    screwTightening = "screwTightening",
    lensReplacement = "lensReplacement"
}
export enum ServiceType {
    eyeTest = "eyeTest",
    combined = "combined",
    frameTryOn = "frameTryOn"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignProviderToBooking(bookingId: bigint, providerId: Principal): Promise<void>;
    createOpticianBooking(serviceType: ServiceType, details: string, address: string, preferredTime: string, price: PriceInfo): Promise<bigint>;
    createRentalBooking(itemId: bigint, rentalPeriod: bigint, address: string, price: PriceInfo): Promise<bigint>;
    createRepairBooking(repairType: RepairType, details: string, address: string, preferredTime: string, price: PriceInfo): Promise<bigint>;
    findAvailableRentalItems(): Promise<Array<RentalItem>>;
    getActiveProviders(): Promise<Array<Provider>>;
    getAllBookings(): Promise<Array<Booking>>;
    getBooking(bookingId: bigint): Promise<Booking>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerBookings(): Promise<Array<Booking>>;
    getProvider(providerId: Principal): Promise<Provider | null>;
    getProviderBookings(): Promise<Array<Booking>>;
    getRentalCatalog(): Promise<Array<RentalItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    onboardProvider(name: string, contact: string, serviceAreas: string, services: Array<ServiceType>, availability: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingType as _BookingType, PriceInfo as _PriceInfo, Provider as _Provider, RepairType as _RepairType, ServiceType as _ServiceType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignProviderToBooking(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignProviderToBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignProviderToBooking(arg0, arg1);
            return result;
        }
    }
    async createOpticianBooking(arg0: ServiceType, arg1: string, arg2: string, arg3: string, arg4: PriceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOpticianBooking(to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOpticianBooking(to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createRentalBooking(arg0: bigint, arg1: bigint, arg2: string, arg3: PriceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRentalBooking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRentalBooking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createRepairBooking(arg0: RepairType, arg1: string, arg2: string, arg3: string, arg4: PriceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairBooking(to_candid_RepairType_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairBooking(to_candid_RepairType_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async findAvailableRentalItems(): Promise<Array<RentalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.findAvailableRentalItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findAvailableRentalItems();
            return result;
        }
    }
    async getActiveProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProviders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProviders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvider(arg0: Principal): Promise<Provider | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRentalCatalog(): Promise<Array<RentalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalCatalog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalCatalog();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async onboardProvider(arg0: string, arg1: string, arg2: string, arg3: Array<ServiceType>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.onboardProvider(arg0, arg1, arg2, to_candid_vec_n29(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.onboardProvider(arg0, arg1, arg2, to_candid_vec_n29(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Provider_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Provider): Provider {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RepairType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairType): RepairType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceType]): ServiceType | null {
    return value.length === 0 ? null : from_candid_ServiceType_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepairType]): RepairType | null {
    return value.length === 0 ? null : from_candid_RepairType_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Provider]): Provider | null {
    return value.length === 0 ? null : from_candid_Provider_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    serviceType: [] | [_ServiceType];
    provider: [] | [Principal];
    customer: Principal;
    createdAt: bigint;
    repairType: [] | [_RepairType];
    updatedAt: bigint;
    address: string;
    bookingType: _BookingType;
    preferredTime: string;
    details: string;
    price: _PriceInfo;
}): {
    id: bigint;
    status: BookingStatus;
    serviceType?: ServiceType;
    provider?: Principal;
    customer: Principal;
    createdAt: bigint;
    repairType?: RepairType;
    updatedAt: bigint;
    address: string;
    bookingType: BookingType;
    preferredTime: string;
    details: string;
    price: PriceInfo;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n16(_uploadFile, _downloadFile, value.status),
        serviceType: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.serviceType)),
        provider: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.provider)),
        customer: value.customer,
        createdAt: value.createdAt,
        repairType: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.repairType)),
        updatedAt: value.updatedAt,
        address: value.address,
        bookingType: from_candid_BookingType_n23(_uploadFile, _downloadFile, value.bookingType),
        preferredTime: value.preferredTime,
        details: value.details,
        price: value.price
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    active: boolean;
    contact: string;
    name: string;
    availability: string;
    serviceAreas: string;
    services: Array<_ServiceType>;
}): {
    id: Principal;
    active: boolean;
    contact: string;
    name: string;
    availability: string;
    serviceAreas: string;
    services: Array<ServiceType>;
} {
    return {
        id: value.id,
        active: value.active,
        contact: value.contact,
        name: value.name,
        availability: value.availability,
        serviceAreas: value.serviceAreas,
        services: from_candid_vec_n10(_uploadFile, _downloadFile, value.services)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eyeTest: null;
} | {
    combined: null;
} | {
    frameTryOn: null;
}): ServiceType {
    return "eyeTest" in value ? ServiceType.eyeTest : "combined" in value ? ServiceType.combined : "frameTryOn" in value ? ServiceType.frameTryOn : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "scheduled" in value ? BookingStatus.scheduled : "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "accepted" in value ? BookingStatus.accepted : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    other: null;
} | {
    screwTightening: null;
} | {
    lensReplacement: null;
}): RepairType {
    return "adjustment" in value ? RepairType.adjustment : "other" in value ? RepairType.other : "screwTightening" in value ? RepairType.screwTightening : "lensReplacement" in value ? RepairType.lensReplacement : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rental: null;
} | {
    repair: null;
} | {
    mobileOptician: null;
}): BookingType {
    return "rental" in value ? BookingType.rental : "repair" in value ? BookingType.repair : "mobileOptician" in value ? BookingType.mobileOptician : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceType>): Array<ServiceType> {
    return value.map((x)=>from_candid_ServiceType_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Provider>): Array<Provider> {
    return value.map((x)=>from_candid_Provider_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_RepairType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairType): _RepairType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.scheduled ? {
        scheduled: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    eyeTest: null;
} | {
    combined: null;
} | {
    frameTryOn: null;
} {
    return value == ServiceType.eyeTest ? {
        eyeTest: null
    } : value == ServiceType.combined ? {
        combined: null
    } : value == ServiceType.frameTryOn ? {
        frameTryOn: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairType): {
    adjustment: null;
} | {
    other: null;
} | {
    screwTightening: null;
} | {
    lensReplacement: null;
} {
    return value == RepairType.adjustment ? {
        adjustment: null
    } : value == RepairType.other ? {
        other: null
    } : value == RepairType.screwTightening ? {
        screwTightening: null
    } : value == RepairType.lensReplacement ? {
        lensReplacement: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceType>): Array<_ServiceType> {
    return value.map((x)=>to_candid_ServiceType_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
