/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RentalItem {
    id: bigint;
    name: string;
    deposit: bigint;
    available: boolean;
    pricePerDay: bigint;
    category: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PriceInfo {
    total: bigint;
    baseFee: bigint;
    addOns: bigint;
}
export interface LogMobileNumberVerification {
    mobileNumber: string;
    verifiedAt: bigint;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    serviceType?: ServiceType;
    provider?: Principal;
    customer: Principal;
    createdAt: bigint;
    mobileNumber?: string;
    updatedAt: bigint;
    repairTypes?: Array<RepairType>;
    address?: string;
    bookingType: BookingType;
    preferredTime?: string;
    details?: string;
    price: PriceInfo;
}
export interface Provider {
    id: Principal;
    active: boolean;
    name: string;
    email: string;
    availability: string;
    phone: string;
    serviceAreas: string;
    services: Array<ServiceType>;
}
export interface UserProfile {
    age: bigint;
    name: string;
    email: string;
    framePreferences?: Array<FrameShape>;
    address: string;
    gender: Gender;
    phone: string;
    profilePicture?: ExternalBlob;
    prescriptionPicture?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum BookingType {
    rental = "rental",
    repair = "repair",
    mobileOptician = "mobileOptician"
}
export enum FrameShape {
    rectangular = "rectangular",
    oval = "oval",
    square = "square",
    aviator = "aviator",
    wayfarer = "wayfarer",
    catEye = "catEye",
    round = "round"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum RepairType {
    adjustment = "adjustment",
    other = "other",
    screwTightening = "screwTightening",
    lensReplacement = "lensReplacement"
}
export enum ServiceType {
    eyeTest = "eyeTest",
    combined = "combined",
    frameTryOn = "frameTryOn"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignProviderToBooking(bookingId: bigint, providerId: Principal): Promise<void>;
    calculateProfileCompletion(): Promise<bigint>;
    createOpticianBooking(serviceType: ServiceType, details: string | null, address: string | null, preferredTime: string | null, price: PriceInfo, mobileNumber: string): Promise<bigint>;
    createRentalBooking(itemId: bigint, rentalPeriod: bigint, address: string, price: PriceInfo): Promise<bigint>;
    createRepairBooking(repairTypes: Array<RepairType>, details: string | null, address: string | null, preferredTime: string | null, price: PriceInfo): Promise<bigint>;
    findAvailableRentalItems(): Promise<Array<RentalItem>>;
    getActiveProviders(): Promise<Array<Provider>>;
    getAllBookings(): Promise<Array<Booking>>;
    getBooking(bookingId: bigint): Promise<Booking>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerBookings(): Promise<Array<Booking>>;
    getMobileNumberVerifications(): Promise<Array<LogMobileNumberVerification>>;
    getProvider(providerId: Principal): Promise<Provider | null>;
    getProviderBookings(): Promise<Array<Booking>>;
    getRentalCatalog(): Promise<Array<RentalItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logMobileNumberVerification(mobileNumber: string): Promise<void>;
    onboardProvider(name: string, phone: string, email: string, serviceAreas: string, services: Array<ServiceType>, availability: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateFramePreferences(newPreferences: Array<FrameShape>): Promise<void>;
    updatePrescriptionPicture(newPicture: ExternalBlob): Promise<void>;
    updateProfilePicture(newPicture: ExternalBlob): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingType as _BookingType, ExternalBlob as _ExternalBlob, FrameShape as _FrameShape, Gender as _Gender, PriceInfo as _PriceInfo, Provider as _Provider, RepairType as _RepairType, ServiceType as _ServiceType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignProviderToBooking(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignProviderToBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignProviderToBooking(arg0, arg1);
            return result;
        }
    }
    async calculateProfileCompletion(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProfileCompletion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProfileCompletion();
            return result;
        }
    }
    async createOpticianBooking(arg0: ServiceType, arg1: string | null, arg2: string | null, arg3: string | null, arg4: PriceInfo, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOpticianBooking(to_candid_ServiceType_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOpticianBooking(to_candid_ServiceType_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createRentalBooking(arg0: bigint, arg1: bigint, arg2: string, arg3: PriceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRentalBooking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRentalBooking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createRepairBooking(arg0: Array<RepairType>, arg1: string | null, arg2: string | null, arg3: string | null, arg4: PriceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairBooking(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairBooking(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async findAvailableRentalItems(): Promise<Array<RentalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.findAvailableRentalItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findAvailableRentalItems();
            return result;
        }
    }
    async getActiveProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProviders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProviders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBookings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBookings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMobileNumberVerifications(): Promise<Array<LogMobileNumberVerification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMobileNumberVerifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMobileNumberVerifications();
            return result;
        }
    }
    async getProvider(arg0: Principal): Promise<Provider | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderBookings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderBookings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRentalCatalog(): Promise<Array<RentalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalCatalog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalCatalog();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logMobileNumberVerification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMobileNumberVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMobileNumberVerification(arg0);
            return result;
        }
    }
    async onboardProvider(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<ServiceType>, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.onboardProvider(arg0, arg1, arg2, arg3, to_candid_vec_n50(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.onboardProvider(arg0, arg1, arg2, arg3, to_candid_vec_n50(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFramePreferences(arg0: Array<FrameShape>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFramePreferences(to_candid_vec_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFramePreferences(to_candid_vec_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePrescriptionPicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescriptionPicture(await to_candid_ExternalBlob_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescriptionPicture(await to_candid_ExternalBlob_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BookingStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FrameShape_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FrameShape): FrameShape {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Provider_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Provider): Provider {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RepairType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairType): RepairType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceType]): ServiceType | null {
    return value.length === 0 ? null : from_candid_ServiceType_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_RepairType>]): Array<RepairType> | null {
    return value.length === 0 ? null : from_candid_vec_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_FrameShape>]): Array<FrameShape> | null {
    return value.length === 0 ? null : from_candid_vec_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Provider]): Provider | null {
    return value.length === 0 ? null : from_candid_Provider_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    active: boolean;
    name: string;
    email: string;
    availability: string;
    phone: string;
    serviceAreas: string;
    services: Array<_ServiceType>;
}): {
    id: Principal;
    active: boolean;
    name: string;
    email: string;
    availability: string;
    phone: string;
    serviceAreas: string;
    services: Array<ServiceType>;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        email: value.email,
        availability: value.availability,
        phone: value.phone,
        serviceAreas: value.serviceAreas,
        services: from_candid_vec_n19(_uploadFile, _downloadFile, value.services)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    serviceType: [] | [_ServiceType];
    provider: [] | [Principal];
    customer: Principal;
    createdAt: bigint;
    mobileNumber: [] | [string];
    updatedAt: bigint;
    repairTypes: [] | [Array<_RepairType>];
    address: [] | [string];
    bookingType: _BookingType;
    preferredTime: [] | [string];
    details: [] | [string];
    price: _PriceInfo;
}): {
    id: bigint;
    status: BookingStatus;
    serviceType?: ServiceType;
    provider?: Principal;
    customer: Principal;
    createdAt: bigint;
    mobileNumber?: string;
    updatedAt: bigint;
    repairTypes?: Array<RepairType>;
    address?: string;
    bookingType: BookingType;
    preferredTime?: string;
    details?: string;
    price: PriceInfo;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n25(_uploadFile, _downloadFile, value.status),
        serviceType: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.serviceType)),
        provider: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.provider)),
        customer: value.customer,
        createdAt: value.createdAt,
        mobileNumber: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.mobileNumber)),
        updatedAt: value.updatedAt,
        repairTypes: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.repairTypes)),
        address: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.address)),
        bookingType: from_candid_BookingType_n34(_uploadFile, _downloadFile, value.bookingType),
        preferredTime: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.preferredTime)),
        details: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.details)),
        price: value.price
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    email: string;
    framePreferences: [] | [Array<_FrameShape>];
    address: string;
    gender: _Gender;
    phone: string;
    profilePicture: [] | [_ExternalBlob];
    prescriptionPicture: [] | [_ExternalBlob];
}): Promise<{
    age: bigint;
    name: string;
    email: string;
    framePreferences?: Array<FrameShape>;
    address: string;
    gender: Gender;
    phone: string;
    profilePicture?: ExternalBlob;
    prescriptionPicture?: ExternalBlob;
}> {
    return {
        age: value.age,
        name: value.name,
        email: value.email,
        framePreferences: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.framePreferences)),
        address: value.address,
        gender: from_candid_Gender_n43(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.profilePicture)),
        prescriptionPicture: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.prescriptionPicture))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eyeTest: null;
} | {
    combined: null;
} | {
    frameTryOn: null;
}): ServiceType {
    return "eyeTest" in value ? ServiceType.eyeTest : "combined" in value ? ServiceType.combined : "frameTryOn" in value ? ServiceType.frameTryOn : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "scheduled" in value ? BookingStatus.scheduled : "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "accepted" in value ? BookingStatus.accepted : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    other: null;
} | {
    screwTightening: null;
} | {
    lensReplacement: null;
}): RepairType {
    return "adjustment" in value ? RepairType.adjustment : "other" in value ? RepairType.other : "screwTightening" in value ? RepairType.screwTightening : "lensReplacement" in value ? RepairType.lensReplacement : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rental: null;
} | {
    repair: null;
} | {
    mobileOptician: null;
}): BookingType {
    return "rental" in value ? BookingType.rental : "repair" in value ? BookingType.repair : "mobileOptician" in value ? BookingType.mobileOptician : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rectangular: null;
} | {
    oval: null;
} | {
    square: null;
} | {
    aviator: null;
} | {
    wayfarer: null;
} | {
    catEye: null;
} | {
    round: null;
}): FrameShape {
    return "rectangular" in value ? FrameShape.rectangular : "oval" in value ? FrameShape.oval : "square" in value ? FrameShape.square : "aviator" in value ? FrameShape.aviator : "wayfarer" in value ? FrameShape.wayfarer : "catEye" in value ? FrameShape.catEye : "round" in value ? FrameShape.round : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Provider>): Array<Provider> {
    return value.map((x)=>from_candid_Provider_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceType>): Array<ServiceType> {
    return value.map((x)=>from_candid_ServiceType_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepairType>): Array<RepairType> {
    return value.map((x)=>from_candid_RepairType_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FrameShape>): Array<FrameShape> {
    return value.map((x)=>from_candid_FrameShape_n41(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FrameShape_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrameShape): _FrameShape {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_RepairType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairType): _RepairType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    email: string;
    framePreferences?: Array<FrameShape>;
    address: string;
    gender: Gender;
    phone: string;
    profilePicture?: ExternalBlob;
    prescriptionPicture?: ExternalBlob;
}): Promise<{
    age: bigint;
    name: string;
    email: string;
    framePreferences: [] | [Array<_FrameShape>];
    address: string;
    gender: _Gender;
    phone: string;
    profilePicture: [] | [_ExternalBlob];
    prescriptionPicture: [] | [_ExternalBlob];
}> {
    return {
        age: value.age,
        name: value.name,
        email: value.email,
        framePreferences: value.framePreferences ? candid_some(to_candid_vec_n53(_uploadFile, _downloadFile, value.framePreferences)) : candid_none(),
        address: value.address,
        gender: to_candid_Gender_n56(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n58(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        prescriptionPicture: value.prescriptionPicture ? candid_some(await to_candid_ExternalBlob_n58(_uploadFile, _downloadFile, value.prescriptionPicture)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    eyeTest: null;
} | {
    combined: null;
} | {
    frameTryOn: null;
} {
    return value == ServiceType.eyeTest ? {
        eyeTest: null
    } : value == ServiceType.combined ? {
        combined: null
    } : value == ServiceType.frameTryOn ? {
        frameTryOn: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairType): {
    adjustment: null;
} | {
    other: null;
} | {
    screwTightening: null;
} | {
    lensReplacement: null;
} {
    return value == RepairType.adjustment ? {
        adjustment: null
    } : value == RepairType.other ? {
        other: null
    } : value == RepairType.screwTightening ? {
        screwTightening: null
    } : value == RepairType.lensReplacement ? {
        lensReplacement: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrameShape): {
    rectangular: null;
} | {
    oval: null;
} | {
    square: null;
} | {
    aviator: null;
} | {
    wayfarer: null;
} | {
    catEye: null;
} | {
    round: null;
} {
    return value == FrameShape.rectangular ? {
        rectangular: null
    } : value == FrameShape.oval ? {
        oval: null
    } : value == FrameShape.square ? {
        square: null
    } : value == FrameShape.aviator ? {
        aviator: null
    } : value == FrameShape.wayfarer ? {
        wayfarer: null
    } : value == FrameShape.catEye ? {
        catEye: null
    } : value == FrameShape.round ? {
        round: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.scheduled ? {
        scheduled: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RepairType>): Array<_RepairType> {
    return value.map((x)=>to_candid_RepairType_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceType>): Array<_ServiceType> {
    return value.map((x)=>to_candid_ServiceType_n10(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FrameShape>): Array<_FrameShape> {
    return value.map((x)=>to_candid_FrameShape_n54(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
